trigger:
- master
- develop
- release/*
- feature/*
- hotfix/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  solution: '**/*.sln'

steps:
- checkout: self
  clean: true
  persistCredentials: true

- task: UseGitVersion@5
  displayName: 'Version Management'
  inputs:
    configFilePath: 'gitversion.yml'
    updateAssemblyInfo: true
    useConfigFile: true
    versionSpec: 5.x

- task: DotNetCoreCLI@2
  displayName: 'Restore Nuget Packages for Solution'
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    arguments: '--configuration $(buildConfiguration) --no-restore'
    command: 'build'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Test Solution'
  inputs:
    arguments: '--configuration $(buildConfiguration) --collect "Code Coverage"'
    command: 'test'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Package Artifacts'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versionEnvVar: 'GitVersion.NuGetVersion'
    versioningScheme: 'byEnvVar'

- task: CopyFiles@2
  displayName: 'Copy Packages for Publish'
  inputs:
    contents: '**/*.nupkg'
    targetFolder: '$(Build.ArtifactStagingDirectory)/Packages'
    sourceFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    artifactName: 'drop'
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/Packages'
    publishLocation: 'Container'