//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MooVC.Syntax.CSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Snippet_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Snippet_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MooVC.Syntax.CSharp.Snippet.Resources", typeof(Snippet_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The options required to format the block..
        /// </summary>
        internal static string BlockOptionsRequired {
            get {
                return ResourceManager.GetString("BlockOptionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The `{0}` for parsing the `{1}` must be provided..
        /// </summary>
        internal static string FromOptionsRequired {
            get {
                return ResourceManager.GetString("FromOptionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The `{0}` must be provided..
        /// </summary>
        internal static string FromValueRequired {
            get {
                return ResourceManager.GetString("FromValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of a single line must be within the acceptable range..
        /// </summary>
        internal static string OptionsMaxLengthOutOfRange {
            get {
                return ResourceManager.GetString("OptionsMaxLengthOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character(s) to mark a new line must be provided..
        /// </summary>
        internal static string OptionsNewLineRequired {
            get {
                return ResourceManager.GetString("OptionsNewLineRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The whitespace to be applied must be provided..
        /// </summary>
        internal static string OptionsWhitespaceRequired {
            get {
                return ResourceManager.GetString("OptionsWhitespaceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The options required to direct the shift must be provided..
        /// </summary>
        internal static string ShiftOptionsRequired {
            get {
                return ResourceManager.GetString("ShiftOptionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The options required to direct formatting must be provided..
        /// </summary>
        internal static string ToStringOptionsRequired {
            get {
                return ResourceManager.GetString("ToStringOptionsRequired", resourceCulture);
            }
        }
    }
}
