//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MooVC.Collections.Generic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MooVC.Collections.Generic.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target collection to which the items are to be added must be provided..
        /// </summary>
        internal static string CollectionExtensionsAddRangeTargetRequired {
            get {
                return ResourceManager.GetString("CollectionExtensionsAddRangeTargetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target collection in which the items are to be replaced must be provided..
        /// </summary>
        internal static string CollectionExtensionsReplaceTargetRequired {
            get {
                return ResourceManager.GetString("CollectionExtensionsReplaceTargetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action to be performed must be provided..
        /// </summary>
        internal static string EnumerableExtensionsActionRequired {
            get {
                return ResourceManager.GetString("EnumerableExtensionsActionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action to be performed in parallel must be provided..
        /// </summary>
        internal static string EnumerableExtensionsForAllActionRequired {
            get {
                return ResourceManager.GetString("EnumerableExtensionsForAllActionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation to be performed in parallel must be provided..
        /// </summary>
        internal static string EnumerableExtensionsForAllAsyncOperationRequired {
            get {
                return ResourceManager.GetString("EnumerableExtensionsForAllAsyncOperationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The predicate to be applied when searching for the index of the first occurance within the enumeration must be provided..
        /// </summary>
        internal static string EnumerableExtensionsIndexOfPredicateRequired {
            get {
                return ResourceManager.GetString("EnumerableExtensionsIndexOfPredicateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transform to be applied in parallel to each element within the enumeration must be provided..
        /// </summary>
        internal static string EnumerableExtensionsProcessAllTransformRequired {
            get {
                return ResourceManager.GetString("EnumerableExtensionsProcessAllTransformRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transform to be applied to each element within the enumeration must be provided..
        /// </summary>
        internal static string EnumerableExtensionsProcessTransformRequired {
            get {
                return ResourceManager.GetString("EnumerableExtensionsProcessTransformRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selector to be applied when ordering the elements within the snapshot must be provided..
        /// </summary>
        internal static string EnumerableExtensionsSnapshotOrderRequired {
            get {
                return ResourceManager.GetString("EnumerableExtensionsSnapshotOrderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The condition that determines whether or not the predicate is to be applied must be provided..
        /// </summary>
        internal static string EnumerableExtensionsWhereIfConditionRequired {
            get {
                return ResourceManager.GetString("EnumerableExtensionsWhereIfConditionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The predicate to be applied to the enumeration when applicable must be provided..
        /// </summary>
        internal static string EnumerableExtensionsWhereIfPredicateRequired {
            get {
                return ResourceManager.GetString("EnumerableExtensionsWhereIfPredicateRequired", resourceCulture);
            }
        }
    }
}
