//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MooVC.Syntax {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Snippet_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Snippet_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MooVC.Syntax.Snippet.Resources", typeof(Snippet_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The opening snippet for the block must be provided..
        /// </summary>
        internal static string BlockOpeningRequired {
            get {
                return ResourceManager.GetString("BlockOpeningRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The options required to format the block..
        /// </summary>
        internal static string BlockOptionsRequired {
            get {
                return ResourceManager.GetString("BlockOptionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The options for chaining must be provided..
        /// </summary>
        internal static string ChainOptionsRequired {
            get {
                return ResourceManager.GetString("ChainOptionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The options to apply when combining the snippets must be provided..
        /// </summary>
        internal static string CombineOptionsRequired {
            get {
                return ResourceManager.GetString("CombineOptionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snippets to combine must be provided..
        /// </summary>
        internal static string CombineSnippetsRequired {
            get {
                return ResourceManager.GetString("CombineSnippetsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The `{0}` for parsing the `{1}` must be provided..
        /// </summary>
        internal static string FromOptionsRequired {
            get {
                return ResourceManager.GetString("FromOptionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The `{0}` must be provided..
        /// </summary>
        internal static string FromValueRequired {
            get {
                return ResourceManager.GetString("FromValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Opening Marker for the Boundary of the Block must be provided..
        /// </summary>
        internal static string OptionsBlockBoundariesClosingRequired {
            get {
                return ResourceManager.GetString("OptionsBlockBoundariesClosingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Closing Marker for the Boundary of the Block must be provided..
        /// </summary>
        internal static string OptionsBlockBoundariesOpeningRequired {
            get {
                return ResourceManager.GetString("OptionsBlockBoundariesOpeningRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Block configuration must be provided..
        /// </summary>
        internal static string OptionsBlockRequired {
            get {
                return ResourceManager.GetString("OptionsBlockRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The style to use for Inline statements must be provided..
        /// </summary>
        internal static string OptionsBlocksInlineRequired {
            get {
                return ResourceManager.GetString("OptionsBlocksInlineRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bracing style must be provided..
        /// </summary>
        internal static string OptionsBlocksLayoutRequired {
            get {
                return ResourceManager.GetString("OptionsBlocksLayoutRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The boundary Markers for the Block must be provided..
        /// </summary>
        internal static string OptionsBlocksMarkersRequired {
            get {
                return ResourceManager.GetString("OptionsBlocksMarkersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chaining configuration must be provided..
        /// </summary>
        internal static string OptionsChainingRequired {
            get {
                return ResourceManager.GetString("OptionsChainingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of a single line must be within the acceptable range..
        /// </summary>
        internal static string OptionsMaxLineLengthOutOfRange {
            get {
                return ResourceManager.GetString("OptionsMaxLineLengthOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The whitespace to be applied must be provided..
        /// </summary>
        internal static string OptionsWhitespaceRequired {
            get {
                return ResourceManager.GetString("OptionsWhitespaceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The options required to direct the shift must be provided..
        /// </summary>
        internal static string ShiftOptionsRequired {
            get {
                return ResourceManager.GetString("ShiftOptionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of `{0}` totaling `{1}` does not match the required amount of `{2}`..
        /// </summary>
        internal static string ValidateLinesMismatch {
            get {
                return ResourceManager.GetString("ValidateLinesMismatch", resourceCulture);
            }
        }
    }
}