//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MooVC.Syntax.Formatting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    /// <summary>
    /// Represents the StringExtensions_Resources.
    /// </summary>
    internal class StringExtensions_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        /// <summary>
        /// Initializes a new instance of the StringExtensions_Resources class.
        /// </summary>
        internal StringExtensions_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MooVC.Syntax.Formatting.StringExtensions.Resources", typeof(StringExtensions_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The formatter to be applied to the elements must be provided..
        /// </summary>
        internal static string CombineFormatterRequired {
            get {
                return ResourceManager.GetString("CombineFormatterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The separator to be applied to the elements must be provided..
        /// </summary>
        internal static string CombineSeparatorRequired {
            get {
                return ResourceManager.GetString("CombineSeparatorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The elements to which separator `{0}` is to be applied must be provided..
        /// </summary>
        internal static string CombineValuesRequired {
            get {
                return ResourceManager.GetString("CombineValuesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value to be rendered in camel case must be provided..
        /// </summary>
        internal static string ToCamelCaseValueRequired {
            get {
                return ResourceManager.GetString("ToCamelCaseValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value to be rendered in kebab case must be provided..
        /// </summary>
        internal static string ToKebabCaseValueRequired {
            get {
                return ResourceManager.GetString("ToKebabCaseValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value to be rendered in pascal case must be provided..
        /// </summary>
        internal static string ToPascalCaseValueRequired {
            get {
                return ResourceManager.GetString("ToPascalCaseValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value to be rendered in snake case must be provided..
        /// </summary>
        internal static string ToSnakeCaseValueRequired {
            get {
                return ResourceManager.GetString("ToSnakeCaseValueRequired", resourceCulture);
            }
        }
    }
}