namespace Muify.Domain
{
    using System;
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.Text;
    using MooVC.Syntax;
    using MooVC.Syntax.CSharp.Concepts;

    [Generator(LanguageNames.CSharp)]
    public sealed class IdentityAttributeGenerator
        : IIncrementalGenerator
    {
        /// <summary>
        /// The hint name used for the code generated by the generator.
        /// </summary>
        internal const string Hint = "IdentityAttribute.g.cs";

        /// <summary>
        /// The name of the attribute (without the suffix).
        /// </summary>
        internal const string Name = "Identity";

        /// <inheritdoc/>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(Generate);
        }

        private static void Generate(IncrementalGeneratorPostInitializationContext context)
        {
            var content = Builder
                .New<Definition>()
                .From("Muify.Domain")
                .For<Class>(@class => @class
                    .Named($"{Name}Attribute")
                    .DerivesFrom(typeof(Attribute)))
                .ToSnippet();

            context.AddSource(Hint, SourceText.From(Content, Encoding.UTF8));
        }
    }
}