//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muify.Domain
{
    using System.Globalization;
    using System.Resources;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IdentityAttributeGenerator_Resources
    {
        private static CultureInfo resourceCulture;

        private static ResourceManager resourceMan;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityAttributeGenerator_Resources()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        internal static string DefinitionIdentityAttributeGeneration
        {
            get
            {
                return ResourceManager.GetString("DefinitionIdentityAttributeGeneration", resourceCulture);
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    var temporaryResourceManager = new ResourceManager("Muify.Domain.IdentityAttributeGenerator.Resources", typeof(IdentityAttributeGenerator_Resources).Assembly);
                    resourceMan = temporaryResourceManager;
                }

                return resourceMan;
            }
        }
    }
}