namespace Muify.Domain
{
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.Text;

    [Generator(LanguageNames.CSharp)]
    public sealed class IdentityAttributeGenerator
        : IIncrementalGenerator
    {
        /// <summary>
        /// The hint name used for the code generated by the generator.
        /// </summary>
        internal const string Hint = "IdentityAttribute.g.cs";

        /// <summary>
        /// The name of the attribute (without the suffix).
        /// </summary>
        internal const string Name = "Identity";

        /// <summary>
        /// Gets the generated content as a formatted string for use by the generator.
        /// </summary>
        /// <value>
        /// The generated content as a formatted string for use by generator.
        /// </value>
        internal static string Content { get; } = string.Format(IdentityAttributeGenerator_Resources.Content, Name);

        /// <inheritdoc/>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(Generate);
        }

        private static void Generate(IncrementalGeneratorPostInitializationContext context)
        {
            context.AddSource(Hint, SourceText.From(Content, Encoding.UTF8));
        }
    }
}