namespace Muify.Domain
{
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.Text;
    using MooVC.Syntax;
    using MooVC.Syntax.CSharp.Concepts;
    using MooVC.Syntax.CSharp.Members;
    using Attribute = System.Attribute;

    [Generator(LanguageNames.CSharp)]
    public sealed class RaisesAttributeGenerator
        : IIncrementalGenerator
    {
        /// <summary>
        /// The hint name used for the code generated by the generator.
        /// </summary>
        internal const string Hint = "RaisesAttribute.g.cs";

        /// <summary>
        /// The name of the attribute (without the suffix).
        /// </summary>
        internal const string Name = "Raises";

        /// <inheritdoc/>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(Generate);
        }

        private static void Generate(IncrementalGeneratorPostInitializationContext context)
        {
            var content = Builder
                .New<Definition>()
                .From(typeof(RaisesAttributeGenerator))
                .For<Class>(@class => @class
                    .DerivesFrom(typeof(Attribute))
                    .WithProperties(name => name
                        .Named("Name")
                        .OfType(typeof(string)))
                    .Named($"{Name}Attribute"))
                .ToSnippet(Configuration.Options);

            context.AddSource(Hint, SourceText.From(content, Encoding.UTF8));
        }
    }
}