name: .NET Build, Test & Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
      
env:
  configuration: 'Release'
  solution: 'MooVC.sln'

jobs:

  build:
    name: Build, Test & Publish
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Use .NET SDKs
      uses: Cysharp/Actions/.github/actions/setup-dotnet@main
      with:
        dotnet-version: |
          5.0.x
          6.0.x
          7.0.x
            
    - name: Restore Nuget Packages for Solution
      run: dotnet restore ${{ env.solution }}

    - name: Get Version from Tag (Push)
      if: github.event_name == 'push'
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Get Latest Tag (Dispatch)
      if: github.event_name == 'workflow_dispatch'
      run: echo "LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
      
    - name: Build Solution
      run: dotnet build ${{ env.solution }} --configuration ${{ env.configuration }} --no-restore /p:Version=${{ env.VERSION }} /p:FileVersion=${{ env.VERSION }} /p:AssemblyVersion=${{ env.VERSION }}

    - name: Test Solution
      run: dotnet test ${{ env.solution }} --configuration ${{ env.configuration }} --no-build

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        
    - name: Pack Solution
      run: dotnet pack ${{ env.solution }} --configuration ${{ env.configuration }} --no-build --output ./artifacts /p:Version=${{ env.VERSION }}

    - name: Publish Packages to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
