name: .NET Build, Test & Publish

on:
  push:
    tags:
      - '*'
      
env:
  configuration: 'Release'
  solution: 'MooVC.sln'

jobs:

  build:
    name: Build, Test & Publish
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Use .NET SDKs
      uses: Cysharp/Actions/.github/actions/setup-dotnet@main
      with:
        dotnet-version: |
          5.0.x
          6.0.x
          7.0.x
            
    - name: Restore Nuget Packages for Solution
      run: dotnet restore ${{ env.solution }}

    - name: Build Solution
      run: dotnet build ${{ env.solution }} --configuration ${{ env.configuration }} --no-restore

    - name: Test Solution
      run: dotnet test ${{ env.solution }} --configuration ${{ env.configuration }} --no-build

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        
    - name: Pack Solution
      run: dotnet pack ${{ env.solution }} --configuration ${{ env.configuration }} --no-build --output ./artifacts

    - name: Publish Packages to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
