name: .NET Build & Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
      - develop
      - release/*
      - feature/*
      - hotfix/*
  schedule:
    - cron: '0 3 * * *'
    
env:
  configuration: 'Debug'
  solution: 'MooVC.sln'
  
jobs:
  build:
    name: Build & Test (.NET ${{ matrix.dotnet }})
    runs-on: windows-latest
    
    strategy:
      matrix:
        dotnet: ['6.0.x', '7.0.x']
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Use .NET SDK
      uses: Cysharp/Actions/.github/actions/setup-dotnet@main
      with:
        dotnet-version: ${{ matrix.dotnet }}
            
    - name: Restore Nuget Packages for Solution
      run: dotnet restore ${{ env.solution }}

    - name: Build Solution
      run: dotnet build ${{ env.solution }} --configuration ${{ env.configuration }} --no-restore

    - name: Test Solution
      run: dotnet test ${{ env.solution }} --configuration ${{ env.configuration }} --no-build

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
