name: .NET Build & Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
      - develop
      - release/*
      - feature/*
      - hotfix/*
  schedule:
    - cron: '0 3 * * *'

env:
  configuration: 'Debug'
  solution: 'MooVC.sln'

jobs:
  build:
    name: Build & Test
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Cache NuGet packages
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
        
    - name: Use .NET SDKs
      uses: Cysharp/Actions/.github/actions/setup-dotnet@main
      with:
        dotnet-version: |
          6.0.x
          7.0.x
            
    - name: Restore Nuget Packages for Solution
      run: dotnet restore ${{ env.solution }}

    - name: Build Solution
      run: dotnet build ${{ env.solution }} --configuration ${{ env.configuration }} --no-restore

    - name: Test Solution
      run: dotnet test ${{ env.solution }} --configuration ${{ env.configuration }} --no-build

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
