name: .NET Build & Test

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop
      - release/*
      - feature/*
      - hotfix/*
  schedule:
    - cron: '0 3 * * *'

env:
  configuration: 'Debug'
  solution: 'src/MooVC.sln'

jobs:

  build:
    name: Build & Test
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Use .NET SDKs
      uses: Cysharp/Actions/.github/actions/setup-dotnet@main
      with:
        dotnet-version: |
          6.0.x
          7.0.x
            
    - name: Restore Nuget Packages for Solution
      run: dotnet restore ${{ env.solution }}

    - name: Build Solution
      run: dotnet build ${{ env.solution }} --configuration ${{ env.configuration }} --no-restore

    - name: Test Solution
      run: dotnet test ${{ env.solution }} --configuration ${{ env.configuration }} --no-build

    - name: Install ReportGenerator Tool for Code Coverage
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Create Code Coverage Reports
      run: reportgenerator "-reports:**/*.cobertura.xml" "-targetdir:coveragereport" -reporttypes:"Cobertura"

    - name: Archive Code Coverage Results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: coveragereport
